/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import java.util.LinkedList;
import java.util.List;

import javax.swing.JFrame;

import model.Contato;
import model.ServicoContatoImpl;
import model.Usuario;

/**
 *
 * @author fabriciogmc
 */
public class TelaPrincipal extends javax.swing.JFrame {

	/**
	 * Creates new form TelaPrincipal
	 * 
	 * @param string
	 */
	public TelaPrincipal(Usuario u) {
		setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
		initComponents(u);
	}

	/**
	 * This method is called from within the constructor to initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is always
	 * regenerated by the Form Editor.
	 * @param u 
	 * @param string 
	 */
	@SuppressWarnings("unchecked")
	// <editor-fold defaultstate="collapsed" desc="Generated
	// Code">//GEN-BEGIN:initComponents
	private void initComponents(Usuario u) {

		jButton1 = new javax.swing.JButton();
		jLabel1 = new javax.swing.JLabel();
		jButton2 = new javax.swing.JButton();
		jButton3 = new javax.swing.JButton();

		jButton1.setText("Buscar Contato");
		jButton1.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				jButton1ActionPerformed(evt, u);
			}
		});

		jLabel1.setText("Opções básicas da agenda de contatos.");

		jButton2.setText("Listar Contatos");
		jButton2.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				jButton2ActionPerformed(evt,u);
			}
		});

		jButton3.setText("Criar Contatos");
		jButton3.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				jButton3ActionPerformed(evt,u);
			}
		});

		javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
		getContentPane().setLayout(layout);
		layout.setHorizontalGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
				.addGroup(layout.createSequentialGroup().addGap(114, 114, 114)
						.addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
								.addComponent(jButton2, javax.swing.GroupLayout.Alignment.LEADING,
										javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE,
										Short.MAX_VALUE)
								.addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE,
										javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
								.addComponent(jButton3, javax.swing.GroupLayout.DEFAULT_SIZE,
										javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
						.addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
				.addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
						.addContainerGap(70, Short.MAX_VALUE).addComponent(jLabel1).addGap(58, 58, 58)));
		layout.setVerticalGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
				.addGroup(layout.createSequentialGroup().addContainerGap().addComponent(jLabel1).addGap(38, 38, 38)
						.addComponent(jButton1).addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
						.addComponent(jButton2).addGap(18, 18, 18).addComponent(jButton3)
						.addContainerGap(107, Short.MAX_VALUE)));
	}// </editor-fold>//GEN-END:initComponents

	private void jButton1ActionPerformed(java.awt.event.ActionEvent evt, Usuario u) {// GEN-FIRST:event_jButton1ActionPerformed
		// TODO add your handling code here:
		
		ServicoContatoImpl servico = new ServicoContatoImpl(u.getNomeUsuario());
		List<Contato> listaContato = new LinkedList<Contato>();
		listaContato = servico.listarTodosContatos();
		u.setContatos(listaContato);
		TelaBusca busca = new TelaBusca(u);
		busca.setVisible(true);
		
		
	}

	private void jButton2ActionPerformed(java.awt.event.ActionEvent evt, Usuario u) {// GEN-FIRST:event_jButton1ActionPerformed
		// TODO add your handling code here:
		
		ServicoContatoImpl servico = new ServicoContatoImpl(u.getNomeUsuario());
		List<Contato> listaContato = new LinkedList<Contato>();
		listaContato = servico.listarTodosContatos();
		u.setContatos(listaContato);
		TelaListagem listagem = new TelaListagem(u.getContatos(), u);
		listagem.setVisible(true);

	}

	private void jButton3ActionPerformed(java.awt.event.ActionEvent evt, Usuario u) {// GEN-FIRST:event_jButton1ActionPerformed
		// TODO add your handling code here:
		int verificador = 1;
		TelaCadastro cadastro = new TelaCadastro(null,u, verificador);
		cadastro.setVisible(true);
		
	}

	// GEN-LAST:event_jButton1ActionPerformed

	// Variables declaration - do not modify//GEN-BEGIN:variables
	private javax.swing.JButton jButton1;
	private javax.swing.JButton jButton2;
	private javax.swing.JButton jButton3;
	private javax.swing.JLabel jLabel1;
	// End of variables declaration//GEN-END:variables
}
