import static
org.junit.jupiter.api.Assertions.assertEquals;
import org.junit.jupiter.api.Test;

import model.UsuarioVerificador;

/*
 * This Java source file was generated by the Gradle 'init' task.
 */

public class CasosDeTestesUsuarios {

	@Test
	public void NomeTest1() {
		UsuarioVerificador verificador = new UsuarioVerificador();
		boolean test = verificador.verifica("");
		assertEquals(false , test);
		}
	
	@Test
	public void NomeTest2() {
		UsuarioVerificador verificador = new UsuarioVerificador();
		boolean test = verificador.verifica("teste");
		assertEquals(true , test);
		}
	
	@Test
	public void NomeTest3() {
		UsuarioVerificador verificador = new UsuarioVerificador();
		boolean test = verificador.verifica("test");
		assertEquals(false , test);
		}
	
	@Test
	public void NomeTest4() {
		UsuarioVerificador verificador = new UsuarioVerificador();
		boolean test = verificador.verifica("teste0123456789t");
		assertEquals(false , test);
		}
	
	@Test
	public void NomeTest5() {
		UsuarioVerificador verificador = new UsuarioVerificador();
		boolean test = verificador.verifica("teste@");
		assertEquals(false , test);
		}
	
	@Test
	public void NomeTest6() {
		UsuarioVerificador verificador = new UsuarioVerificador();
		boolean test = verificador.verifica("     ");
		assertEquals(false , test);
		}
	
	@Test
	public void NomeTest7() {
		UsuarioVerificador verificador = new UsuarioVerificador();
		boolean test = verificador.verifica("testa0123456789");
		assertEquals(true , test);
		}
	
	@Test
	public void NomeTest8() {
		UsuarioVerificador verificador = new UsuarioVerificador();
		boolean test = verificador.verifica("0123456789");
		assertEquals(true , test);
		}
	
	@Test
	public void NomeTest9() {
		UsuarioVerificador verificador = new UsuarioVerificador();
		boolean test = verificador.verifica("Testa1");
		assertEquals(true , test);
		}
	
	@Test
	public void NomeTest10() {
		UsuarioVerificador verificador = new UsuarioVerificador();
		boolean test = verificador.verifica("0123456789");
		assertEquals(true , test);
		}
	
	@Test
	public void SenhaTest1() {
		UsuarioVerificador verificador = new UsuarioVerificador();
		boolean test = verificador.verifica("test");
		assertEquals(false , test);
		}
	
	@Test
	public void SenhaTest2() {
		UsuarioVerificador verificador = new UsuarioVerificador();
		boolean test = verificador.verifica("teste0123456789t");
		assertEquals(false , test);
		}
	
	@Test
	public void SenhaTest3() {
		UsuarioVerificador verificador = new UsuarioVerificador();
		boolean test = verificador.verifica("teste0123456789");
		assertEquals(true , test);
		}
	
	@Test
	public void SenhaTest4() {
		UsuarioVerificador verificador = new UsuarioVerificador();
		boolean test = verificador.verifica("teste");
		assertEquals(true , test);
		}
}
