
/*
 * This Java source file was generated by the Gradle 'init' task.
 */

import static
org.junit.jupiter.api.Assertions.assertEquals;
import org.junit.jupiter.api.Test;

import model.ContatoDAOImpl;
import model.UsuarioTxtExiste;

import java.util.LinkedList;
import java.util.List;

import model.Contato;

public class ContatoDAOImplTeste {

	@Test
	public void testInserir() {
		ContatoDAOImpl classUnderTest = new ContatoDAOImpl("usuario1");
		ContatoDAOImpl editador = new ContatoDAOImpl("usuario1");
		UsuarioTxtExiste edita = new UsuarioTxtExiste();
		Contato c = new Contato();
		c.setNome("contato1");
		c.setTelefone("12345678");
		c.setEmail("ct@ct.com");
		c.setEndereco("av brasil");
		edita.criaTxtData("usuario1");
		assertEquals(c, classUnderTest.inserir(c));
		editador.removerContato(c);
		edita.deletaTxtData("usuario1");
	}

	@Test
	public void testBuscarNome() {
		ContatoDAOImpl classUnderTest = new ContatoDAOImpl("usuario1");
		ContatoDAOImpl editador = new ContatoDAOImpl("usuario1");
		UsuarioTxtExiste edita = new UsuarioTxtExiste();
		Contato c = new Contato();
		c.setNome("contato1");
		c.setTelefone("12345678");
		c.setEmail("ct@ct.com");
		c.setEndereco("av brasil");
		edita.criaTxtData("usuario1");
		editador.inserir(c);
		assertEquals(c, classUnderTest.buscarPorParteNome("cont"));
		editador.removerContato(c);
		edita.deletaTxtData("usuario1");
	}

	@Test
	public void testRemover() {
		ContatoDAOImpl classUnderTest = new ContatoDAOImpl("usuario1");
		ContatoDAOImpl editador = new ContatoDAOImpl("usuario1");
		UsuarioTxtExiste edita = new UsuarioTxtExiste();
		Contato c = new Contato();
		c.setNome("contato1");
		c.setTelefone("12345678");
		c.setEmail("ct@ct.com");
		c.setEndereco("av brasil");
		edita.criaTxtData("usuario1");
		editador.inserir(c);
		assertEquals(true, classUnderTest.removerContato(c));
		editador.removerContato(c);
		edita.deletaTxtData("usuario1");
	}
	
	@Test
	public void testAtualizar() {
		ContatoDAOImpl classUnderTest = new ContatoDAOImpl("usuario1");
		ContatoDAOImpl editador = new ContatoDAOImpl("usuario1");
		UsuarioTxtExiste edita = new UsuarioTxtExiste();
		edita.criaTxtData("usuario1");
		Contato c = new Contato();
		c.setNome("contato2");
		c.setTelefone("12345678");
		c.setEmail("ct@ct.com");
		c.setEndereco("av brasil");
		Contato c2 = new Contato();
		c2 = editador.inserir(c);
		assertEquals(c, classUnderTest.atualizarContato(c2, c));
		editador.removerContato(c);
		edita.deletaTxtData("usuario1");
	}
	
	@Test
	public void testListar() {
		ContatoDAOImpl classUnderTest = new ContatoDAOImpl("usuario1");
		ContatoDAOImpl editador = new ContatoDAOImpl("usuario1");
		UsuarioTxtExiste edita = new UsuarioTxtExiste();
		List<Contato> lista = new LinkedList<Contato>();
		edita.criaTxtData("usuario1");
		Contato c = new Contato();
		c.setNome("contato1");
		c.setTelefone("12345678");
		c.setEmail("ct@ct.com");
		c.setEndereco("av brasil");
		lista.add(c);
		editador.inserir(c);
		assertEquals(lista.size(), classUnderTest.listarTodosContatos().size());
		editador.removerContato(c);
	}
}
