
/*
 * This Java source file was generated by the Gradle 'init' task.
 */

import static
org.junit.jupiter.api.Assertions.assertEquals;
import org.junit.jupiter.api.Test;

import java.util.LinkedList;
import java.util.List;

import model.ServicoUsuarioImpl;
import view.TelaCadastroUsuarioAgenda;
import model.Usuario;


public class InterfaceGraficaTest {

	@Test
	public void testTelaCadastroUsuario() {
		TelaCadastroUsuarioAgenda tela = new TelaCadastroUsuarioAgenda();
		tela.setVisible(true);
		tela.jTextField1.setText("jefferson10");
		tela.jTextField2.setText("jefferson10");
		tela.jTextField3.setText("jefferson10");
		tela.jButton1.doClick();
		ServicoUsuarioImpl servico = new ServicoUsuarioImpl("users");
		List<Usuario> lista = new LinkedList<Usuario>();
		List<Usuario> lista2 = new LinkedList<Usuario>();
		lista = servico.listarTodosUsuarios();
		Usuario u = new Usuario();
		u.setNomeUsuario("jefferson10");
		u.setSenha("jefferson10");
		lista2.add(u);
		assertEquals(lista.size(), lista2.size());
		Usuario remover = new Usuario();
		remover.setNomeUsuario("jefferson10");
		remover.setSenha("jefferson10");
		servico.removerUsuario(remover);
	}
}
