
/*
 * This Java source file was generated by the Gradle 'init' task.
 */
import static
org.junit.jupiter.api.Assertions.assertEquals;
import org.junit.jupiter.api.Test;

import model.ServicoUsuarioImpl;

import java.util.LinkedList;
import java.util.List;

import model.Usuario;

import model.Contato;

public class ServicoUsuarioImplTeste {
	
	@Test
	public void testInserir() {
		ServicoUsuarioImpl classUnderTest = new ServicoUsuarioImpl("users");
		Usuario u = new Usuario();
		u.setNomeUsuario("jefferson10");
		u.setSenha("jefferson10");
		assertEquals(u, classUnderTest.inserir(u));
		ServicoUsuarioImpl remover = new ServicoUsuarioImpl("users");
		remover.removerUsuario(u);
	}
	
	@Test
	public void testBusca() {
		ServicoUsuarioImpl classUnderTest = new ServicoUsuarioImpl("users");
		Usuario u = new Usuario();
		u.setNomeUsuario("xvxdulr3");
		u.setSenha("xvxdulr3");
		Usuario u2 = new Usuario();
		u2.setNomeUsuario("usuario3");
		u2.setSenha("usuario3");
		classUnderTest.inserir(u2);
		assertEquals(u, classUnderTest.buscarPorNomeUsuario("usuario3"));
		ServicoUsuarioImpl remover = new ServicoUsuarioImpl("users");
		remover.removerUsuario(u2);
	}

	@Test
	public void testRemover() {
		ServicoUsuarioImpl classUnderTest = new ServicoUsuarioImpl("users");
		Usuario u = new Usuario();
		Usuario u2 = new Usuario();
		u2.setNomeUsuario("usuario10");
		u2.setSenha("usuario10");
		ServicoUsuarioImpl popular = new ServicoUsuarioImpl("users");
		popular.inserir(u2);
		u.setNomeUsuario("usuario10");
		u.setSenha("usuario10");
		assertEquals(true, classUnderTest.removerUsuario(u));
		ServicoUsuarioImpl remover = new ServicoUsuarioImpl("users");
		remover.removerUsuario(u);
	}
	
	@Test
	public void testAtualizar() {
		ServicoUsuarioImpl classUnderTest = new ServicoUsuarioImpl("users");
		Usuario uAnt = new Usuario();
		Usuario u2 = new Usuario();
		u2.setNomeUsuario("usuario12");
		u2.setSenha("usuario12");
		ServicoUsuarioImpl popular = new ServicoUsuarioImpl("users");
		popular.inserir(u2);
		uAnt.setNomeUsuario("usuario12");
		uAnt.setSenha("usuario12");
		Usuario uAtual = new Usuario();
		uAtual.setNomeUsuario("restringido1");
		uAtual.setSenha("restringido1");
		List<Contato> listar = new LinkedList<Contato>();
		uAtual.setContatos(listar);
		assertEquals(uAtual, classUnderTest.atualizarUsuario(uAnt, uAtual));
		ServicoUsuarioImpl remover = new ServicoUsuarioImpl("users");
		remover.removerUsuario(uAtual);
	}

	@Test
	public void testListar() {
		ServicoUsuarioImpl classUnderTest = new ServicoUsuarioImpl("users");
		List<Usuario> lista = new LinkedList<Usuario>();
		for (int count = 0; count <= 5; count++) {
			Usuario u = new Usuario();
			u.setNomeUsuario("usuario" + count);
			u.setSenha("usuario" + count);
			lista.add(u);
			classUnderTest.inserir(u);
		}
		assertEquals(lista.size(), classUnderTest.listarTodosUsuarios().size());
		ServicoUsuarioImpl remover = new ServicoUsuarioImpl("users");
		for (int count = 0; count <= 5; count++) {
			Usuario u = new Usuario();
			u.setNomeUsuario("usuario" + count);
			u.setSenha("usuario" + count);
			remover.removerUsuario(u);
		}
	}
	
	@Test
	public void testInserirString() {
		ServicoUsuarioImpl classUnderTest = new ServicoUsuarioImpl("users");
		ServicoUsuarioImpl remover = new ServicoUsuarioImpl("users");
		Usuario u = new Usuario();
		u.setNomeUsuario("korolov10");
		u.setSenha("korolov10");
		assertEquals(u, classUnderTest.inserir("korolov10", "korolov10", null));
		remover.removerUsuario(u);
	}
}
