/*
 * This Java source file was generated by the Gradle 'init' task.
 */
import static
org.junit.jupiter.api.Assertions.assertEquals;
import org.junit.jupiter.api.Test;

import model.UsuarioDAOImpl;

import java.util.LinkedList;
import java.util.List;

import model.Usuario;
import model.Cesar;
import model.Contato;

public class UsuarioDAOImplTeste {

	@Test
	public void testInserir() {
		UsuarioDAOImpl classUnderTest = new UsuarioDAOImpl("users");
		Usuario u = new Usuario();
		u.setNomeUsuario("jefferson10");
		u.setSenha("jefferson10");
		assertEquals(u, classUnderTest.inserir(u));
		UsuarioDAOImpl remover = new UsuarioDAOImpl("users");
		remover.removerUsuario(u);
	}
	
	@Test
	public void testBusca() {
		UsuarioDAOImpl classUnderTest = new UsuarioDAOImpl("users");
		UsuarioDAOImpl remover = new UsuarioDAOImpl("users");
		Usuario u = new Usuario();
		Cesar cesar = new Cesar();
		String nomeEnc = cesar.decriptar(3, "usuario3");
		String senhaEnc = cesar.decriptar(3, "usuario3");
		u.setNomeUsuario(nomeEnc);
		u.setSenha(senhaEnc);
		remover.inserir(u);
		assertEquals(u, classUnderTest.buscarPorNomeUsuario("usuario3"));
		remover.removerUsuario(u);
	}

	@Test
	public void testRemover() {
		UsuarioDAOImpl classUnderTest = new UsuarioDAOImpl("users");
		Usuario u = new Usuario();
		Usuario u2 = new Usuario();
		u2.setNomeUsuario("usuario10");
		u2.setSenha("usuario10");
		UsuarioDAOImpl popular = new UsuarioDAOImpl("users");
		popular.inserir(u2);
		u.setNomeUsuario("usuario10");
		u.setSenha("usuario10");
		assertEquals(true, classUnderTest.removerUsuario(u));
		UsuarioDAOImpl remover = new UsuarioDAOImpl("users");
		remover.removerUsuario(u2);
	}
	
	@Test
	public void testAtualizar() {
		UsuarioDAOImpl classUnderTest = new UsuarioDAOImpl("users");
		Usuario uAnt = new Usuario();
		Usuario u2 = new Usuario();
		u2.setNomeUsuario("usuario12");
		u2.setSenha("usuario12");
		UsuarioDAOImpl popular = new UsuarioDAOImpl("users");
		popular.inserir(u2);
		uAnt.setNomeUsuario("usuario12");
		uAnt.setSenha("usuario12");
		Usuario uAtual = new Usuario();
		uAtual.setNomeUsuario("restringido1");
		uAtual.setSenha("restringido1");
		List<Contato> listar = new LinkedList<Contato>();
		uAtual.setContatos(listar);
		assertEquals(uAtual, classUnderTest.atualizarUsuario(uAnt, uAtual));
		UsuarioDAOImpl remover = new UsuarioDAOImpl("users");
		remover.removerUsuario(uAtual);
	}

	@Test
	public void testListar() {
		UsuarioDAOImpl classUnderTest = new UsuarioDAOImpl("users");
		UsuarioDAOImpl editar = new UsuarioDAOImpl("users");
		List<Usuario> lista = new LinkedList<Usuario>();
		for (int count = 0; count <= 5; count++) {
			Usuario u = new Usuario();
			u.setNomeUsuario("usuario" + count);
			u.setSenha("usuario" + count);
			lista.add(u);
			editar.inserir(u);
		}
		assertEquals(lista.size(), classUnderTest.listarTodosUsuarios().size());
		for (int count = 0; count <= 5; count++) {
			Usuario u = new Usuario();
			u.setNomeUsuario("usuario" + count);
			u.setSenha("usuario" + count);
			editar.removerUsuario(u);
		}
	}
}
